version: "3" 
services: 
    nginx: 
        image: nginx 
        volumes: 
          - ./src:/src 
          - ./default.conf:/etc/nginx/conf.d/default.conf 
        depends_on: 
          - mysql 
          - php 
        ports: 
          - "1000:80" 
        restart: always 
    php: 
        build:
            context: ./
            dockerfile: php.Dockerfile
        volumes: 
          - ./src:/src 
          - ./php.ini:/usr/local/etc/php/php.ini 
        restart: always 
    mysql: 
        image: mysql 
        env_file: 
            - .env 
        restart: always 
        volumes: 
            - ./db-mysql:/var/lib/mysql 
        ports: 
            - "3306:3306" 
    phpmyadmin: 
        image: phpmyadmin:latest
        env_file: 
            - .env 
        ports: 
            - "1050:80" 
        restart: always 
        volumes: 
            - ./php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql